### ISSUE TITLE
config.yml: if there is no package name, build all packages in the project

### ISSUE THREAD

**Issue by tpokorra** [SolidCharity/LightBuildServer#34]
this should make it easier if all packages in the project should be built anyway, for the same distros:

```
Projects:
  myproject:
    Distros: ["fedora/20/amd64", "debian/wheezy/amd64"]
```

instead of:

```
Projects:
  myproject:
    package1:
      Distros: ["fedora/20/amd64", "debian/wheezy/amd64"]
    package2:
      Distros: ["fedora/20/amd64", "debian/wheezy/amd64"]
    package3:
      Distros: ["fedora/20/amd64", "debian/wheezy/amd64"]
```
