### ISSUE TITLE
download sources: option to give new name

### ISSUE THREAD

**Issue by tpokorra** [SolidCharity/LightBuildServer#74]
when I am downloading several source tar.gz files from github, they are all called master.tar.gz

this should work:

```
lbs:
  source:
    download: 
      Release2014_11.tar.gz: "http://github.com/SolidCharity/OpenPetraNow/archive/Release2014_11.tar.gz"
      base.yml.gz: "http://downloads.sourceforge.net/project/openpetraorg/openpetraorg/demodata/base.yml.gz"
      plugin_bankimport.tar.gz: "https://github.com/SolidCharity/OpenPetraPlugin_Bankimport/archive/master.tar.gz"
      plugin_bankimport_csv.tar.gz: "https://github.com/SolidCharity/OpenPetraPlugin_BankimportCSV/archive/master.tar.gz"
```
