### ISSUE TITLE
multiple build containers: keep some build order per user and OS

### ISSUE THREAD

**Issue by tpokorra** [SolidCharity/LightBuildServer#93]
do not distribute builds for same user and OS to several build containers.
this way we keep the order as intended when initiating the builds

eg. can build kolab nightly packages on 3 different build containers: one for CentOS6, one for CentOS7, and one for Debian.

still perhaps we need to add some dependancy in the config.yml?
nightly kolab sync runs on CentOS, but affects Debian nightly builds as well.
So if nightly build is started, and nightly sync is still in the queue, it has to wait.

**Comment by tpokorra** [comment]
examples:

* dependancy of a package "kolab-test/kolab-test" on another project "kolab-nightly".
* dependancy of a project "kolab-nightly" on another project "kolab-nightly-sync".

in `config.yml`:

```
        kolab-test:
           kolab-test:
             DependsOn: ["kolab-nightly"]
             Branches: ["master", "Kolab3.4"]
             Distros: ["centos/6/amd64", "centos/7/amd64", "debian/wheezy/amd64", "ubuntu/trusty/amd64"]
         kolab-sync:
           updatecode:
             Branches: ["Kolab:Development", "Kolab:3.4", "Kolab:3.4:Updates"]
             Distros: ["centos/7/amd64"]
         kolab-nightly-sync:
           updatecodeLBS:
             Distros: ["centos/6/amd64"]
           updatecode:
             Distros: ["centos/6/amd64"]
         kolab-nightly:
          DependsOn: ["kolab-nightly-sync"]
          Distros: ["centos/6/amd64", "centos/7/amd64", "debian/wheezy/amd64"]
          Packages:
           chwala:
           iRony:
           kolab-freebusy:
           kolab-syncroton:
           kolab-utils:
           kolab-webadmin:
           libcalendaring:
           libkolab:
           libkolabxml:
           php-pear-Net-LDAP3:
           pykolab:
           roundcubemail-plugins-kolab:
```
